name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Prepare release artifact
        run: |
          mkdir -p releaseGAA/frontend
          cp -r frontend/build releaseGAA/frontend/
          cp -r backend releaseGAA/

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: releaseGAA
          path: releaseGAA/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: releaseGAA
          path: ./releaseGAA

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "urlshortener-app"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./releaseGAA"
