name: Build and deploy Node.js app to Azure Web App urlshortener-app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Build frontend
        env:
          CI: false
        run: |
          cd frontend
          npm run build

      - name: Prepare ReleaseGAA Artifact Structure
        run: |
          mkdir -p releaseGAA/frontend
          mkdir -p releaseGAA/backend
          cp -r frontend/build releaseGAA/frontend/
          cp -r backend/* releaseGAA/backend/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "urlshortener-app"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: releaseGAA/
